Update bla6nk.yml

diff --git a/.github/workflows/bla6nk.yml b/.github/workflows/bla6nk.yml
--- a/.github/workflows/bla6nk.yml
+++ b/.github/workflows/bla6nk.yml
@@ -18,16 +18,18 @@ jobs:
       - name: Install ZeroTier
         run: |
           $url = "https://install.zerotier.com/"
-          Invoke-WebRequest -Uri $url -OutFile zerotier-install.msi
-          Start-Process -Wait -FilePath "msiexec.exe" -ArgumentList "/i", "$(System.DefaultWorkingDirectory)\zerotier-install.msi", "/quiet", "/norestart"
+          Invoke-WebRequest -Uri $url -OutFile zerotier-install.ps1
+          Get-Content zerotier-install.ps1 | Set-Content -NoNewline -Path zerotier-install-updated.ps1
+          .\zerotier-install-updated.ps1
 
       - name: Join ZeroTier network
         run: |
-          Start-Process -Wait -FilePath "C:\Program Files\ZeroTier One\ZeroTier One.exe" -ArgumentList "join", $env:ZEROTIER_NETWORK_ID
-
-      - name: List contents of the directory
-        run: |
-          Get-ChildItem -Path "C:\Program Files\ZeroTier One"
+          $zerotierPath = Get-Command "zerotier-cli.exe" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
+          if (-not $zerotierPath) {
+            Write-Error "zerotier-cli executable not found."
+            exit 1
+          }
+          Start-Process -FilePath $zerotierPath -ArgumentList "join", $env:ZEROTIER_NETWORK_ID -Wait
 
       - name: Enable RDP
         run: |
